# Generated by Django 4.1.4 on 2023-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='event')),
            ],
        ),
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='FAQs')),
            ],
        ),
        migrations.CreateModel(
            name='galleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='lslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
            ],
        ),
        migrations.CreateModel(
            name='noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='notice')),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('meaning', models.CharField(max_length=50)),
                ('example', models.CharField(max_length=500)),
            ],
        ),
    ]
