# Generated by Django 4.1.4 on 2023-05-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_faqs_image_faqs_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faqs',
            old_name='heading',
            new_name='question',
        ),
    ]
