# Generated by Django 4.1.4 on 2023-05-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_faqs_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='galleries',
            new_name='gallerie',
        ),
    ]
