# Generated by Django 4.1.4 on 2023-05-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_galleries_gallerie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboard',
            old_name='heading',
            new_name='subject',
        ),
    ]
